### ISSUE TITLE
Jupyter/PythonAPI problem with nouveau driver on SUSE

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3466]
Note: I'll upgrade to the proprietary NVIDIA driver to see if that helps and update this ticket once tested.

Graphics info:
```
(base) vapor@localhost:~/mambaforge/envs/3.9.0/lib/python3.9/site-packages/vapor/example_notebooks> inxi -G -c0
Graphics:
  Device-1: NVIDIA GM107GL [Quadro K620] driver: nouveau v: kernel
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 22.1.5 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: zink gpu: nouveau
    resolution: 1355x1080~60Hz
  API: OpenGL v: 4.5 Mesa 22.3.5 renderer: llvmpipe (LLVM 15.0.7 256 bits)
```

Issue:
![nouveauDriverNotFound](https://github.com/NCAR/VAPOR/assets/9522770/3bf04117-09f8-4873-bd2c-e55100bf28f3)
![nouveauDriverNotFound2](https://github.com/NCAR/VAPOR/assets/9522770/ddb95e7b-5126-48b2-bf31-746bd468e0a2)
